# metadata_builder.py
import argparse
import json
from pathlib import Path

def build_metadata(script_path: Path):
    print(f"[*] Extracting metadata from {script_path.name}...")
    text = script_path.read_text(encoding="utf-8")
    
    # Heuristic: Extract Title from the source marker of the Collision phase
    # Example: [COLLISION] (Source: Video Title Here)
    title_match = next((line for line in text.splitlines() if "[COLLISION]" in line), "WENDIGO NARRATIVE")
    title = title_match.split("(Source: ")[-1].replace(")", "").strip()
    
    # DESCRIPTION ASSEMBLY
    description = (
        f"WENDIGO NARRATIVE FORGE - Forensic Output\n\n"
        f"This asset was autonomously synthesized from high-resonance semantic intersections.\n\n"
        f"--- TOPICS ---\n"
        f"Truth, Systemic Control, Future Evolution\n\n"
        f"Generated by WENDIGO C.I.S. (Continuous Infiltration & Synthesis)"
    )

    tags = ["ai", "narrative", "truth", "future", "system", "wendigo"]

    meta = {
        "title": title[:100], # YouTube limit
        "description": description,
        "tags": tags,
        "categoryId": "22",
        "privacyStatus": "private"
    }
    
    return meta

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--script", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    
    meta = build_metadata(Path(args.script))
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)
    print(f"[✅] Metadata packed: {args.out}")
