# metadata_builder.py
import argparse
import json
import re
from pathlib import Path
from typing import List, Dict

def extract_primary_hook(hooks_path: Path) -> str:
    if hooks_path.exists():
        with open(hooks_path, "r", encoding="utf-8") as f:
            hooks = json.load(f)
            if hooks:
                return hooks[0]['text']
    return "WENDIGO NARRATIVE"

def build_titles(primary_hook: str, title_from_script: str) -> List[str]:
    # Aim for 45-70 chars, useful for YT
    variants = []
    
    # 1. The Hook (Direct)
    variants.append(primary_hook[:70])
    
    # 2. How/Why pattern
    variants.append(f"How {primary_hook}"[:70])
    
    # 3. Source + Mystery
    variants.append(f"{title_from_script}: The Hidden Truth"[:70])
    
    # 4. Short Impact
    words = primary_hook.split()
    variants.append(" ".join(words[:5]) + " (Full Breakdown)")
    
    # 5. Question/Challenge
    variants.append(f"Is this the future of {words[0]}?")
    
    return [v.strip() for v in variants[:5]]

def build_thumbnail_text(primary_hook: str) -> List[str]:
    # 2-5 words max
    words = primary_hook.split()
    variants = [
        " ".join(words[:3]),
        "THE TRUTH",
        "SYSTEM CONTROL",
        "DO NOT IGNORE"
    ]
    return [v.upper() for v in variants[:3]]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--script", type=Path, required=True)
    parser.add_argument("--obsessions", type=Path, required=True)
    parser.add_argument("--hooks", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    # Load Inputs
    script_text = args.script.read_text(encoding="utf-8")
    primary_hook = extract_primary_hook(args.hooks)
    
    # Extract Title from Source Marker in script
    title_match = re.search(r"\(Source:\s*(.+)\)", script_text)
    source_title = title_match.group(1).strip() if title_match else "Unknown Source"
    
    # Obsessions
    obs_text = args.obsessions.read_text(encoding="utf-8")
    top_terms = [line.split()[0] for line in obs_text.splitlines() if line.strip()][:15]
    
    # Arcs
    arcs_match = re.findall(r"Arcs:\s*(.+)", script_text)
    unique_arcs = sorted(list(set([a.strip() for line in arcs_match for a in line.split(",")])))

    # Output Generation
    title_variants = build_titles(primary_hook, source_title)
    thumb_variants = build_thumbnail_text(primary_hook)
    
    short_desc = primary_hook[:150] + "..."
    
    description = (
        f"{primary_hook}\n\n"
        f"--- THE NARRATIVE ---\n"
        f"{script_text.split('---')[0].strip()}\n\n"
        f"--- SYSTEMIC ARCS ---\n"
        f"{', '.join(unique_arcs).upper()}\n\n"
        f"--- TAGS ---\n"
        f"{' '.join(['#' + t.capitalize() for t in unique_arcs])} #Wendigo #Forensic\n\n"
        f"Generated by WENDIGO C.I.S. (Continuous Infiltration & Synthesis)"
    )

    tags = list(set(unique_arcs + top_terms + ["wendigo", "truth"]))[:20]
    hashtags = ["#" + t.capitalize() for t in unique_arcs] + ["#Wendigo"]

    metadata = {
        "primary_hook": primary_hook,
        "title_variants": title_variants,
        "thumbnail_text_variants": thumb_variants,
        "description": description,
        "short_description": short_desc,
        "tags": tags,
        "hashtags": hashtags,
        "pinned_comment": f"What is the ground truth of {source_title}? Let's dive in. 👇"
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    print(f"[✅] Metadata Forge Complete. Results: {args.out}")

if __name__ == "__main__":
    main()
