# youtube_uploader.py
import os
import json
import argparse
import pickle
from pathlib import Path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.http import MediaFileUpload

# SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
SCOPES = ["https://www.googleapis.com/auth/youtube.force-ssl"]

def get_service(client_secrets_file, token_file):
    creds = None
    if os.path.exists(token_file):
        with open(token_file, "rb") as token:
            creds = pickle.load(token)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets_file, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(token_file, "wb") as token:
            pickle.dump(creds, token)
    
    return build("youtube", "v3", credentials=creds)

def upload_video(youtube, video_file, title, description, tags, privacy_status="private"):
    print(f"[*] Starting resumable upload of {video_file}...")
    
    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags,
            "categoryId": "22" # People & Blogs
        },
        "status": {
            "privacyStatus": privacy_status,
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(
        video_file, 
        chunksize=1024*1024, # 1MB chunks
        resumable=True,
        mimetype="video/mp4"
    )

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"  [>] Upload Progress: {int(status.progress() * 100)}%")

    print(f"[✅] Upload Complete! Video ID: {response['id']}")
    return response

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--video", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--description", default="Generated by WENDIGO C.I.S.")
    parser.add_argument("--tags", default="")
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--secrets", default="configs/client_secrets.json")
    parser.add_argument("--token", default="configs/youtube_token.pickle")
    args = parser.parse_args()

    youtube = get_service(args.secrets, args.token)
    
    tags_list = [t.strip() for t in args.tags.split(",") if t.strip()]
    
    response = upload_video(
        youtube, 
        args.video, 
        args.title, 
        args.description, 
        tags_list,
        privacy_status="private" # Mandatory staging
    )

    manifest = {
        "run_id": args.run_id,
        "video_id": response["id"],
        "file": args.video,
        "title": args.title,
        "privacyStatus": "private",
        "upload_status": "uploaded"
    }

    manifest_path = Path(f"outputs/publish/{args.run_id}_manifest.json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    
    print(f"[✅] Manifest written: {manifest_path}")

if __name__ == "__main__":
    main()
